### ISSUE TITLE
Add more filter options for projects

### ISSUE THREAD

**Issue by naman14** [naman14/Hacktoberfest-Android#1]
We are currently only using Language to filter projects. We can also add keywords, sorting options etc

**Comment by ItsT-Mo** [comment]
I will try adding more filter options! :)

**Comment by shubham171294** [comment]
What's the status of this issue?

**Comment by naman14** [comment]
More filter options were added in https://github.com/naman14/Hacktoberfest-Android/pull/12
Closing this issue now
