### ISSUE TITLE
Store last loaded username

### ISSUE THREAD

**Issue by ItsT-Mo** [naman14/Hacktoberfest-Android#7]
## Problem
When opening the app, the searchbar should be prefilled with the last username the user has searched for.

This makes checking ones progress easier, since you don't have to keep entering your own username over and over again.

## Proposed Solution
Store the username in the apps preferences

## Will you work on the issue?
Yes, I will submit a PR shortly.

**Comment by Empty2k12** [comment]
Luckily, I created this PR 2 hours ago: https://github.com/naman14/Hacktoberfest-Android/pull/4

**Comment by ItsT-Mo** [comment]
Closed because PR is already open
